language: cpp
compiler:
  - gcc
  - clang
script:
  - cd test/
  - make run
branches:
  only:
    - master
    - 1.8.7
notifications:
  recipients:
    - shalecraig@gmail.com
  email:
    on_success: change
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
