language: cpp
compiler:
  - gcc
  - clang
script:
  - make run
notifications:
  recipients:
    - shalecraig@gmail.com
  email:
    on_success: change
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
